spring.application.name=voting
spring.datasource.url=jdbc:postgresql://localhost:5432/voting
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false